spring.application.name=Estalvia
server.port=8080
spring.main.web-application-type=servlet
logging.level.org.springframework.web=DEBUG
spring.mvc.log-resolved-exception=true
spring.jpa.hibernate.ddl-auto=validate
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=estalviaapp@gmail.com
spring.mail.password=tbgx lmfx lzbc cgar
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
